all:  21 22
21:
	/home/jfclere/JAVA/jdk-21/bin/java --enable-preview  --source 21 --enable-native-access=ALL-UNNAMED version.java
22:
	/home/jfclere/JAVA/jdk-22/bin/java --enable-native-access=ALL-UNNAMED version22.java
